  language: generic
  sudo: required
  services: 
    - docker
  
  before_install:
    - docker build -t jogesh22/react-app -f Dockerfile.dev .
  
  script:
    - docker run -e CI=true jogesh22/react-app npm run test
   