  version: "3"
  services:
    react-app:
      restart: always
      build: 
        context: .
        dockerfile: Dockerfile.dev
      ports:
        - "3004:3000"
      volumes:
        -  /app/node_modules
        -  .:/app